inherit_mode:
  merge:
    - Exclude
    - Include
AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - config/initializer/*
  Exclude:
    - db/**/*
    - bin/*
    - config/**/*
    - vendor/**/*
    - lib/tasks/dev.rake
    - lib/tasks/auto_annotate_models.rake
Bundler/OrderedGems:
  Exclude:
    - Gemfile
Metrics/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/factories/*
    - spec/support/*
    - Guardfile
Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile
Naming/MethodParameterName:
  AllowedNames: [ex]
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
